openapi: 3.0.3
info:
  title: LogOut JSON Server
  description: This is a LogOut JSON Server
  contact:
    name: API Support
    email: trmtikko@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
servers:
  - url: https://trmti--og-ut.deno.dev
    description: jsonServer
paths:
  /NFTJsonData?personal_id={personalId}:
    $ref: './paths/NFTJsonData/index.yaml'
    parameters:
      - name: personalId
        in: path
        description: personalDataのID
        required: true
        schema:
          type: integer
  /metaData:
    $ref: './paths/metaData/index.yaml'
  /personalData:
    $ref: './paths/personalData/index.yaml'
  /personalData/addDamage:
    $ref: './paths/personalData/addDamage.yaml'
  /personalData/addSleepLog:
    $ref: './paths/personalData/addSleepLog.yaml'
  /calculateMint:
    $ref: './paths/calculateMintVol/index.yaml'
